# Generated by Django 4.0.4 on 2022-07-01 04:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('back_account_number', models.CharField(max_length=500)),
                ('opening_balance', models.DecimalField(decimal_places=4, max_digits=18)),
                ('is_system_value', models.BooleanField()),
                ('created_date', models.DateTimeField()),
                ('modified_date', models.DateTimeField(null=True)),
                ('version', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('memo', models.CharField(max_length=500, null=True)),
                ('is_system_value', models.BooleanField()),
                ('created_date', models.DateTimeField()),
                ('modified_date', models.DateTimeField(null=True)),
                ('version', models.IntegerField()),
                ('created_by', models.ForeignKey(db_column='created_by', on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(db_column='modified_by', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='model_category_modified_by_fk_auth_user_id', to=settings.AUTH_USER_MODEL)),
                ('parent_id', models.ForeignKey(db_column='parent_id', on_delete=django.db.models.deletion.DO_NOTHING, to='model.category')),
            ],
        ),
        migrations.CreateModel(
            name='Configuration',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('key_name', models.CharField(max_length=100)),
                ('value', models.CharField(max_length=100)),
                ('memo', models.CharField(max_length=500, null=True)),
                ('type', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ConfigurationParam',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('configuration_key_type', models.CharField(max_length=300)),
                ('value', models.CharField(max_length=300)),
                ('name', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('memo', models.CharField(max_length=500, null=True)),
                ('is_system_value', models.BooleanField()),
                ('created_date', models.DateTimeField()),
                ('modified_date', models.DateTimeField(null=True)),
                ('version', models.IntegerField()),
                ('created_by', models.ForeignKey(db_column='created_by', on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(db_column='modified_by', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='model_customer_modified_by_fk_auth_user_id', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='NotificationDeviceToken',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('device_token', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='PhotoAndVideo',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('sort_order', models.IntegerField()),
                ('file_name', models.CharField(max_length=200)),
                ('user_account_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('key_name', models.CharField(max_length=100)),
                ('created_date', models.DateTimeField()),
                ('modified_date', models.DateTimeField(null=True)),
                ('version', models.IntegerField()),
                ('created_by', models.ForeignKey(db_column='created_by', on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(db_column='modified_by', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='model_status_modified_by_fk_auth_user_id', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('memo', models.CharField(max_length=500, null=True)),
                ('is_system_value', models.BooleanField()),
                ('created_date', models.DateTimeField()),
                ('modified_date', models.DateTimeField(null=True)),
                ('version', models.IntegerField()),
                ('created_by', models.ForeignKey(db_column='created_by', on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(db_column='modified_by', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='model_payment_method_modified_by_fk_auth_user_id', to=settings.AUTH_USER_MODEL)),
                ('status_id', models.ForeignKey(db_column='status_id', on_delete=django.db.models.deletion.DO_NOTHING, to='model.status')),
            ],
        ),
        migrations.CreateModel(
            name='IncomeOrExpense',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('type', models.IntegerField()),
                ('amount', models.DecimalField(decimal_places=4, max_digits=18)),
                ('transaction_date', models.DateTimeField()),
                ('memo', models.CharField(max_length=500, null=True)),
                ('is_system_value', models.BooleanField()),
                ('created_date', models.DateTimeField()),
                ('modified_date', models.DateTimeField(null=True)),
                ('version', models.IntegerField()),
                ('account_id', models.ForeignKey(db_column='account_id', on_delete=django.db.models.deletion.DO_NOTHING, to='model.account')),
                ('category_id', models.ForeignKey(db_column='category_id', on_delete=django.db.models.deletion.DO_NOTHING, to='model.category')),
                ('created_by', models.ForeignKey(db_column='created_by', on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('customer_id', models.ForeignKey(db_column='customer_id', on_delete=django.db.models.deletion.DO_NOTHING, to='model.customer')),
                ('modified_by', models.ForeignKey(db_column='modified_by', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='model_income_or_expense_modified_by_fk_auth_user_id', to=settings.AUTH_USER_MODEL)),
                ('payment_method_id', models.ForeignKey(db_column='payment_method_id', on_delete=django.db.models.deletion.DO_NOTHING, to='model.paymentmethod')),
                ('status_id', models.ForeignKey(db_column='status_id', on_delete=django.db.models.deletion.DO_NOTHING, to='model.status')),
            ],
        ),
        migrations.CreateModel(
            name='GlobalParam',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('key_name', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=100)),
                ('value1', models.IntegerField(null=True)),
                ('value2', models.CharField(max_length=100, null=True)),
                ('memo', models.CharField(max_length=500, null=True)),
                ('status_id', models.ForeignKey(db_column='status_id', on_delete=django.db.models.deletion.DO_NOTHING, to='model.status')),
            ],
        ),
        migrations.CreateModel(
            name='FileDocument',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('transaction_no', models.CharField(max_length=50)),
                ('key_name', models.CharField(max_length=50)),
                ('file_name', models.CharField(max_length=200)),
                ('file_extension', models.CharField(max_length=5)),
                ('file_type', models.IntegerField()),
                ('income_or_expense_id', models.ForeignKey(db_column='income_or_expense_id', on_delete=django.db.models.deletion.DO_NOTHING, to='model.incomeorexpense')),
            ],
        ),
        migrations.CreateModel(
            name='ErrorReport',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('module_name', models.CharField(max_length=100)),
                ('message', models.CharField(max_length=4000)),
                ('created_date', models.DateTimeField()),
                ('created_by', models.ForeignKey(db_column='created_by', on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='customer',
            name='status_id',
            field=models.ForeignKey(db_column='status_id', on_delete=django.db.models.deletion.DO_NOTHING, to='model.status'),
        ),
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('is_base_currency', models.BooleanField()),
                ('abbreviate', models.CharField(max_length=100)),
                ('memo', models.CharField(max_length=500, null=True)),
                ('is_system_value', models.BooleanField()),
                ('created_date', models.DateTimeField()),
                ('modified_date', models.DateTimeField(null=True)),
                ('version', models.IntegerField()),
                ('created_by', models.ForeignKey(db_column='created_by', on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(db_column='modified_by', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='model_currency_modified_by_fk_auth_user_id', to=settings.AUTH_USER_MODEL)),
                ('status_id', models.ForeignKey(db_column='status_id', on_delete=django.db.models.deletion.DO_NOTHING, to='model.status')),
            ],
        ),
        migrations.AddField(
            model_name='category',
            name='status_id',
            field=models.ForeignKey(db_column='status_id', on_delete=django.db.models.deletion.DO_NOTHING, to='model.status'),
        ),
        migrations.CreateModel(
            name='AccountType',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('memo', models.CharField(max_length=500, null=True)),
                ('is_system_value', models.BooleanField()),
                ('created_date', models.DateTimeField()),
                ('modified_date', models.DateTimeField(null=True)),
                ('version', models.IntegerField()),
                ('created_by', models.ForeignKey(db_column='created_by', on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(db_column='modified_by', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='model_account_type_modified_by_fk_auth_user_id', to=settings.AUTH_USER_MODEL)),
                ('status_id', models.ForeignKey(db_column='status_id', on_delete=django.db.models.deletion.DO_NOTHING, to='model.status')),
            ],
        ),
        migrations.AddField(
            model_name='account',
            name='account_type_id',
            field=models.ForeignKey(db_column='account_type_id', on_delete=django.db.models.deletion.DO_NOTHING, to='model.accounttype'),
        ),
        migrations.AddField(
            model_name='account',
            name='created_by',
            field=models.ForeignKey(db_column='created_by', on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='account',
            name='currency_id',
            field=models.ForeignKey(db_column='currency_id', on_delete=django.db.models.deletion.DO_NOTHING, to='model.currency'),
        ),
        migrations.AddField(
            model_name='account',
            name='modified_by',
            field=models.ForeignKey(db_column='modified_by', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='model_account_modified_by_fk_auth_user_id', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='account',
            name='status_id',
            field=models.ForeignKey(db_column='status_id', on_delete=django.db.models.deletion.DO_NOTHING, to='model.status'),
        ),
    ]
