# Generated by Django 4.0.4 on 2022-07-01 05:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('model', '0002_alter_status_modified_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='modified_by',
            field=models.ForeignKey(blank=True, db_column='modified_by', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='model_account_modified_by_fk_auth_user_id', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='account',
            name='modified_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='accounttype',
            name='modified_by',
            field=models.ForeignKey(blank=True, db_column='modified_by', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='model_account_type_modified_by_fk_auth_user_id', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='accounttype',
            name='modified_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='modified_by',
            field=models.ForeignKey(blank=True, db_column='modified_by', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='model_category_modified_by_fk_auth_user_id', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='category',
            name='modified_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='currency',
            name='modified_by',
            field=models.ForeignKey(blank=True, db_column='modified_by', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='model_currency_modified_by_fk_auth_user_id', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='currency',
            name='modified_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='modified_by',
            field=models.ForeignKey(blank=True, db_column='modified_by', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='model_customer_modified_by_fk_auth_user_id', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='customer',
            name='modified_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='incomeorexpense',
            name='modified_by',
            field=models.ForeignKey(blank=True, db_column='modified_by', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='model_income_or_expense_modified_by_fk_auth_user_id', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='incomeorexpense',
            name='modified_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='modified_by',
            field=models.ForeignKey(blank=True, db_column='modified_by', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='model_payment_method_modified_by_fk_auth_user_id', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='modified_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='status',
            name='modified_by',
            field=models.ForeignKey(blank=True, db_column='modified_by', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='model_status_modified_by_fk_auth_user_id', to=settings.AUTH_USER_MODEL),
        ),
    ]
