# Generated by Django 4.0.4 on 2022-07-01 06:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0004_alter_accounttype_memo_alter_category_memo_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Test',
        ),
    ]
