# Generated by Django 4.0.6 on 2022-07-07 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0006_alter_category_parent_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photoandvideo',
            name='user_account_id',
        ),
    ]
