# Generated by Django 4.0.6 on 2022-07-07 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0007_remove_photoandvideo_user_account_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='photoandvideo',
            name='user_account_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
