# Generated by Django 4.0.6 on 2022-07-10 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0008_photoandvideo_user_account_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photoandvideo',
            name='user_account_id',
            field=models.IntegerField(default=3),
            preserve_default=False,
        ),
    ]
