# Generated by Django 4.0.6 on 2022-07-10 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0010_alter_photoandvideo_user_account_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='AAAA',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('sort_order', models.IntegerField()),
            ],
        ),
    ]
