# Generated by Django 4.0.6 on 2022-07-10 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0011_aaaa'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AAAA',
        ),
    ]
