# Generated by Django 4.0.6 on 2022-07-15 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0012_delete_aaaa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuration',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='configuration',
            name='type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='configuration',
            name='value',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
