# Generated by Django 4.0.6 on 2022-08-06 01:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0015_authusertoken'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AuthUserToken',
        ),
    ]
