# Generated by Django 4.0.6 on 2022-08-06 01:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('model', '0016_delete_authusertoken'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthUserToken',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('token', models.TextField()),
                ('expires_in', models.DateTimeField()),
                ('user_account_id', models.ForeignKey(db_column='user_account_id', on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
