# Generated by Django 4.0.6 on 2022-08-08 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0017_authusertoken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='back_account_number',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
