# Generated by Django 4.0.6 on 2022-08-09 13:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('model', '0019_category_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='incomeorexpense',
            name='user_account_id',
            field=models.ForeignKey(blank=True, db_column='user_account_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='model_income_or_expense_user_account_id_by_fk_auth_user_id', to=settings.AUTH_USER_MODEL),
        ),
    ]
