# Generated by Django 4.0.6 on 2022-08-09 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0020_incomeorexpense_user_account_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='incomeorexpense',
            name='customer_id',
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
