# Generated by Django 4.0.6 on 2022-08-09 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0021_remove_incomeorexpense_customer_id_delete_customer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filedocument',
            name='income_or_expense_id',
        ),
        migrations.DeleteModel(
            name='IncomeOrExpense',
        ),
    ]
