# Generated by Django 4.0.6 on 2022-08-09 14:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('model', '0022_remove_filedocument_income_or_expense_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='IncomeOrExpense',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('type', models.IntegerField()),
                ('amount', models.DecimalField(decimal_places=4, max_digits=18)),
                ('transaction_date', models.DateTimeField()),
                ('memo', models.CharField(blank=True, max_length=500, null=True)),
                ('is_system_value', models.BooleanField()),
                ('created_date', models.DateTimeField()),
                ('modified_date', models.DateTimeField(blank=True, null=True)),
                ('version', models.IntegerField()),
                ('account_id', models.ForeignKey(db_column='account_id', on_delete=django.db.models.deletion.DO_NOTHING, to='model.account')),
                ('category_id', models.ForeignKey(db_column='category_id', on_delete=django.db.models.deletion.DO_NOTHING, to='model.category')),
                ('created_by', models.ForeignKey(db_column='created_by', on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, db_column='modified_by', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='model_income_or_expense_modified_by_fk_auth_user_id', to=settings.AUTH_USER_MODEL)),
                ('payment_method_id', models.ForeignKey(db_column='payment_method_id', on_delete=django.db.models.deletion.DO_NOTHING, to='model.paymentmethod')),
                ('status_id', models.ForeignKey(db_column='status_id', on_delete=django.db.models.deletion.DO_NOTHING, to='model.status')),
                ('user_account_id', models.ForeignKey(db_column='user_account_id', on_delete=django.db.models.deletion.DO_NOTHING, related_name='model_income_or_expense_user_account_id_by_fk_auth_user_id', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
