# Generated by Django 4.0.6 on 2022-08-09 14:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0023_incomeorexpense'),
    ]

    operations = [
        migrations.AddField(
            model_name='filedocument',
            name='income_or_expense_id',
            field=models.ForeignKey(blank=True, db_column='income_or_expense_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='model.incomeorexpense'),
        ),
    ]
