# Generated by Django 4.0.6 on 2022-08-14 04:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0024_filedocument_income_or_expense_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filedocument',
            name='income_or_expense_id',
        ),
        migrations.DeleteModel(
            name='IncomeOrExpense',
        ),
    ]
