# Generated by Django 4.0.6 on 2022-08-14 05:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0027_filedocument_income_or_expense_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='incomeorexpense',
            name='transaction_type_id',
        ),
        migrations.AddField(
            model_name='incomeorexpense',
            name='global_param_id',
            field=models.ForeignKey(blank=True, db_column='global_param_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='model.globalparam'),
        ),
    ]
