# Generated by Django 4.0.6 on 2022-08-14 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0028_remove_incomeorexpense_transaction_type_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='globalparam',
            name='value1',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='globalparam',
            name='value2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
